repos:
  - repo: local
    hooks:
      - id: stylua-check
        name: Stylua Check
        entry: stylua --check
        language: system
        types: [lua]

      - id: prettier-check
        name: Prettier check
        entry: prettier --check
        language: system
        types: [json, yaml]
